### ISSUE TITLE
Bug: Cant loot quest items.

### ISSUE THREAD

**Issue by brunolopes1996** [azerothcore/mod-aoe-loot#24]
### Current Behaviour

Human starting zone, Wolf meat quest, you requiete a stack of 8 items droped by the wolfs.
I kill the wolfs they do show the item in the loot plus other items the mob drops, i click to loot the items all the items get into my bags except the quest item that just vanishes. ( it does not go to the mail it does not go to my bags and it does not count to the quest complition)
if i turn the module off everything works as intended i can loot the mob take the items requiered for the quest.

### Expected Behaviour

The item should appear on my bag and count for the quest completition when looted

### Steps to reproduce the problem

Create a human, take the wolf meat quest on the starting zone and try to loot the requested items to complete the quest 

### AC rev. hash/commit

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots cloned 19/02/2024

### Operating system

windows

### Custom changes or Modules

- Eluna.
- Autobalance.
- Transmog.
- AH bot.
- Individual XP.
- Solo LFG.

**Comment by pangolp** [comment]
The module is still in development, although what you mention should not happen. Later, I will clone the repository and try what you mention. Thanks for the report.

**Comment by pangolp** [comment]
Unfortunately, the problem is in a mechanic that we implemented, because if we used the original, sometimes, in certain circumstances, it gave us more items than usual. The problem is that if we go back to that mechanic, to enable the quest items issue, we are going to have that other problem. So it's time to investigate a little more in detail.

**Comment by pangolp** [comment]
I think I found the fault. There are 2 vectors.
```c++
std::vector<LootItem> items;
std::vector<LootItem> quest_items;
```
I am only using the first one, so surely, in the second one, there are all the mission items, and for that reason, they are not being delivered. It's not that serious I think, it may be easy to repair it.
