### ISSUE TITLE
Bug: Fewer quest items when mod is enabled

### ISSUE THREAD

**Issue by imevul** [azerothcore/mod-aoe-loot#29]
### Current Behaviour

At least some quests (noticed it on Jewelcrafting daily and the WG loot quests, like Warding the Warriors, A Rare Herb, etc) take much longer to complete with the mod enabled, even when killing individual enemies and looting them one by one. This is as a solo player (not in party).

I am unsure if other drop rates are affected.

### Expected Behaviour

Drop rates for quest items should be the same, with or without the mod enabled.

### Steps to reproduce the problem

1. Start WG quest (Warding the Warriors or A Rare Herb) with mod enabled. (Solo player, not in group)
2. Notice abysmal drop rates.
3. Disable mod in config and restart server.
4. Notice drop rates immediately improved.

### Extra Notes

Videos showing the issue:
Mod AoE disabled, works fine: https://youtu.be/lPvvlMJutZI
Mod AoE enabled, can't loot quest items: https://youtu.be/e_UgoxD0Do8

Quest in the videos is one of these two:
https://www.wowhead.com/wotlk/quest=13153/warding-the-warriors
https://www.wowhead.com/wotlk/quest=13198/warding-the-warriors

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/c47c945aa420

### Operating system

Ubuntu 22.04.3 LTS (x64)

### Custom changes or Modules

- mod-account-achievements
- mod-accountbound
- mod-ah-bot
- mod-aoe-loot
- mod-eluna
- mod-guildhouse
- mod-learn-spells
- mod-reagent-bank-account
- mod-solo-lfg
- mod-solocraft
- mod-transmog

**Comment by pangolp** [comment]
Hello, good afternoon. I'm going to review what you mention, but it's strange, given that the mod at no time makes any changes related to that topic. What the mod does is go through the bodies in a given radius, obtain the items, add them to a list, and then add them to the player. In any case, it is a mod that is in development, and we have not been able to finish it yet. It may have some faults. If you can edit the report, and add the links to the missions you mention for testing, I will appreciate it. And if you want to attach a video, uploading it to YouTube, even in private, that also works for me.

**Comment by pangolp** [comment]
Are these links correct?

- https://www.wowhead.com/wotlk/es/quest=13153/warding-the-warriors
- https://www.wowhead.com/wotlk/quest=13195/a-rare-herb
- https://www.wowhead.com/wotlk/item=44809/horde-herb-pouch
- https://www.wowhead.com/wotlk/es/item=44808/armadura-de-la-horda-imbuida

**Comment by imevul** [comment]
Yes, they are correct.

**Comment by imevul** [comment]
I updated the bug report with video links. It is very obvious that something is not working correctly. The quest items are part of the visible loot, but do not get looted. (Even when clicked on directly)

**Comment by pangolp** [comment]
Perfect, I'll check it out, thanks for the report. Anyway, I was watching the videos, and I can't see the topic well, because apparently the screen size is too big. The objects can barely be distinguished, but anyway, it serves as proof for me. I'll see what I can find out.

**Comment by pangolp** [comment]
Initially, the module was intended to be used alone, if the person was outside of a group. Then, it mutated and it still does. We are improving by trying to write, and correct the errors that are reported. Because we haven't tested all the features yet. So all the reports that arrive, as long as they are not repeated, are welcome.

**Comment by imevul** [comment]
Ah, sorry about the screen size.  Didn't think that would be an issue. If it helps I can upload another video tomorrow after work with a more reasonable aspect ratio.

**Comment by pangolp** [comment]
> Ah, sorry about the screen size.  Didn't think that would be an issue. If it helps I can upload another video tomorrow after work with a more reasonable aspect ratio.

There's no need. More or less he understood the problem. Now we have to find the cause and fix it.

**Comment by pangolp** [comment]
Good afternoon, I want to apologize, but so far, there are other issues related to the module that I have also been able to correct. I'm trying to correct them all. If I cannot correct the problems that currently arise, we would have to go back to the original idea, which was to use it only when the player is alone, and make some modification, for when the player enters a dungeon through the search engine, with the module that allows you to enter alone.

**Comment by pangolp** [comment]
I think that with the next fix, it has to be solved.
Try it and let me know if it works.
As soon as I pass the tests, I merge it.
I've been testing it, and it seems to work.

**Comment by imevul** [comment]
Nice! I'll try it out later today and let you know if I find any issues.

**Comment by pangolp** [comment]
Perfect. Thank you.

**Comment by imevul** [comment]
Seems the latest update broke mailing items when inventory is full.

Also, looks like the gold handling might not be 100% correct. As far as I can tell, the gold is distributed correctly, but sometimes (auto-loot enabled) the loot window will still show up, and the gold is the only item left in the "loot bag". (Minor issue)
Tested the gold issue solo, in solo instance, solo LFG, and in a group.

**Comment by pangolp** [comment]
> Seems the latest update broke mailing items when inventory is full.
> 
> Also, looks like the gold handling might not be 100% correct. As far as I can tell, the gold is distributed correctly, but sometimes (auto-loot enabled) the loot window will still show up, and the gold is the only item left in the "loot bag". (Minor issue) Tested the gold issue solo, in solo instance, solo LFG, and in a group.

Well, could you do a report on that topic? So I start working on it. The gold was the last thing I added.

And regarding the issue of email, if possible, you also need another report, but separately, so I can work on the issues in isolation, doing tests.

Thank you.

**Comment by pangolp** [comment]
The change was too big, that's why some things may have escaped me. But I will try to fix them, so that it is 100% functional as soon as possible. But I need the reports please, if possible, separately, because although they are from the same module, they are different problems.

**Comment by aristoblis** [comment]
Seems this issue was not fixed yet. Quest items still get left on mobs.  Doesn't matter if you are questing alone, in a group, or with bots. Quest items, and probably other items as well, are being left behind on mobs after looting.

**Comment by pangolp** [comment]
> Seems this issue was not fixed yet. Quest items still get left on mobs.  Doesn't matter if you are questing alone, in a group, or with bots. Quest items, and probably other items as well, are being left behind on mobs after looting.

The customer has a limit of 18 items. So some items are left in the bodies. When it exceeds the limit, it divides between the remaining bodies. But if it is less than 18, it grabs them all.
