### ISSUE TITLE
Feature: Disable Chat Announce

### ISSUE THREAD

**Issue by F-Lambda** [azerothcore/mod-aoe-loot#39]
### Describe your feature request or suggestion in detail

Would it be possible to add a flag to disable the chat announce on login? Specifically the "This server is running the Loot aoe module." message.

**Comment by pangolp** [comment]
> ### Describe your feature request or suggestion in detail
> 
> Would it be possible to add a flag to disable the chat announce on login? Specifically the "This server is running the Loot aoe module." message.

Of course it's possible to add that. The question is, why? Why does that message bother you, being shown only once when entering the kingdom?
